apiVersion: v1
kind: Pod
metadata:
  name: nettools
  namespace: tripviewer
spec:
  containers:
  - name: nettools
    image: mcastelino/nettools
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
    command: ["ping", "8.8.8.8"]

