apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: tripviewer
  labels:
    app: tripviewer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: tripviewer 
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: tripviewer
  namespace: tripviewer
spec:
  selector:
    matchLabels:
      app: tripviewer
  replicas: 1
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer 
        image: registryxna8703.azurecr.io/tripviewer:1.0  # or just image: redis
        ports:
        - containerPort: 80
        env:
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile:8080"
        - name: TRIPS_API_ENDPOINT
          value: "http://trips-api:8080"
        - name: BING_MAPS_KEY
          value: "AkVOLc2-fEUo6AjN0w1JpICwbIOzwiIBFdAlP8LNBaCfFnLkBt9V0R4C3oHrBbHz"

          
